services:
  # Main FastAPI application
  app:
    build:
      context: .
      dockerfile: docker/full-app/Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: ${DOCKER_USERNAME}/football-game-tracking-app:${TAG}  # Replace with your docker hub username/repo (ex: export DOCKER_USERNAME=mjolif)
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    environment:
      - OLLAMA_URL=http://ollama:11434/api/generate
    depends_on:
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    networks:
      - football-net

  # Ollama server
  ollama:
    build:
      context: .
      dockerfile: docker/ollama/Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
      args:
        OLLAMA_MODEL: smollm2:1.7b
    ports:
      - "11434:11434"
    image: ${DOCKER_USERNAME}/football-game-tracking-ollama:${TAG} # Replace with your docker hub username/repo (ex: export DOCKER_USERNAME=mjolif)
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - football-net
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

networks:
  football-net:
    driver: bridge

volumes:
  uploads:
  outputs:
  ollama-data: